config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'
  resources :articles do
  		resources :comments
  	end
  	resources :tags
  	resources :users

  	resources :user_sessions, only: [ :new, :create, :destroy]

  	get 'login' => 'user_sessions#new'
  	get 'logout'=> 'user_sessions#destroy'
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	#has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
	#validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	def tag_list
		tags.join(", ")
	end
	def tag_list=(tags_string)
		tag_names = tags_string.split(", ").collect{ |s| s.strip.downcase }.uniq
		new_or_found_tags = tag_names.collect{|name| Tag.find_or_create_by(name: name)}
		self.tags = new_or_found_tags
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings

	def to_s
		name
	end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	include UserSessionsHelper
	before_filter :loginCheck, except: [:index, :show]
	before_filter :require_login, except: [:index, :show]
	
	
	def index
		@articles = Article.all
	end
	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		
		@comment.article_id = @article.id
	end
	def new
		@article = Article.new
	end
	def create
		@article = Article.new(article_params)
		@article.save

		flash.notice = "Article #{@article.title} Created!" 
		redirect_to article_path(@article)
	end
	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		flash.notice = "Article #{@article.title} Deleted!" 

		redirect_to articles_path
	end
	def edit
		@article = Article.find(params[:id])
	end
	def update
		@article = Article.find(params[:id])
		@article.update(article_params)

		flash.notice = "Article #{@article.title} Updated!" 

		redirect_to article_path(@article)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_filter :require_login, except: [:create]
	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]

		@comment.save

		flash.notice = "Comment by #{@comment.author_name} Created!" 
		redirect_to article_path(@comment.article)
	end

	private
	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end 
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	include UserSessionsHelper
	before_filter :loginCheck, only: [:destroy]
	before_filter :require_login, only: [:destroy]
	def index
		@tags = Tag.all
	end
	def show
		@tag = Tag.find(params[:id])
	end
	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy

		if Tag.count.zero?
	    	redirect_to articles_path
	    else
	    	redirect_to tags_path
	    end
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

	def new
	end

	def create
		if login(params[:email], params[:password])
			redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
		else
			flash.notice = "Login failed!"
			render action: :new
		end
	end

	def destroy
		logout
		redirect_to(:users, notice: 'Logged out!')
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :zero_users_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]


  def zero_users_or_authenticated
    unless User.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	private
	def article_params
    	params.require(:article).permit(:title, :body, :tag_list )#:image)
  	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
	private
	def loginCheck
		flash.notice = "Must be logged in!" if !logged_in?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_comment.html.erb
<div>
	<h4>Comment by <%= comment.author_name %> </h4>
	<p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
	<p class ="comment"> <%= comment.body %></p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
	<ul>
		<% @article.errors.full_messages.each do |error| %>
    		<li><%= error %></li>
  		<% end %>
	</ul>
	<p>
		<%= f.label :title %> <br/>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %> <br/>
		<%= f.text_area :body %> 
	</p>
	<p>
	 	<%= f.label :image, "Attach an Image" %><br />
 		<%= f.file_field :image %>
	</p>
	<p>
		<%=f.submit %>
	</p>
	<p>
		<%=f.label :tag_list %><br/>
		<%=f.text_field :tag_list %>
	</p>
<%end%>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1> All Articles </h1>
<% if Article.count == 0 %>
	<h3>No Articles</h3>
<%end%>

<table id ="articles">
	<tr>
		
			<th><h3>Title </h3></th>
			<th><h3> Body </h3></th>
			<th><h3>Tags </h3></th>
	</tr>
	<% @articles.each do |article| %>
		<tr>
			<td>
				<%= link_to article.title, article_path(article)%>
			</td>
			<td>
				<% body = article.body.slice(0..25) %>
				<% if body != article.body %>
					<%body << "..." %>
				<%end%>
				<%=body%>
			</td>
			<td>
				<%=article.tags.join(", ") %>
			</td>
		</tr>
	<%end%>
</table>
<%= link_to "Create a new Article", new_article_path, class: "new_article" %><br/><br/>
<%= link_to "View all/edit tags", tags_path %>

app/views/articles/new.html.erb
<h1>Create a new Article</h1>
<%= render partial: 'form' %>
<%=link_to "<< Back to Article List", articles_path %>

app/views/articles/show.html.erb
<h1><%=@article.title%></h1>
<p>
	Tags:
	<% @article.tags.each do |tag| %>
		<%=link_to tag.name, tag_path(tag) %>
	<%end%>
</p>
<h3><%=@article.body %></h3> 
<% if logged_in? %>	
	<%= render partial: 'comments/form' %> 
<% end %>
<h3>Comments (<%=@article.comments.size%>)</h3>
	<%= render partial: 'comment', collection: @article.comments %>
<% if logged_in? %>	
	<%= link_to "edit", edit_article_path(@article) %> <br/>
	<%= link_to "delete", article_path(@article), method: :delete, data:{confirm: "Really delete this article?"} %> <br/>
<% end %>
<%= link_to "<< Back to List of Articles", articles_path %>

app/views/comments/_form.html.erb
<h3>Post a Comment </h3>

<%= form_for [@article, @comment ] do |f| %>
	<p>
		<%= f.label :author_name, "Your Name" %></br>
		<%= f.text_field :author_name %>
	</p>
	<p> <%= f.label :body %></br>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit 'Submit' %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="flash">
    <%= flash.notice %>
  </p>
  <div id="container">
    <div id="content">
      <%= yield %>
      <hr>
      <h6>
        <% if logged_in? %>
          <%= "Logged in as #{current_user.email}" %>
          <%= link_to "(logout)", logout_path %>
        <% else %>
          <%= link_to "(login)", login_path %>
        <% end %>
      </h6>
    </div>
  </div>
</body>
</html>

app/views/tags/index.html.erb
<h1> All Tags</h1>
<% if Tag.count == 0 %>
	<h3>No Tags</h3>
<%end%>
<% @tags.each do |tag| %>
	<ul>
		<%=link_to "delete", tag_path(tag), method: :delete %> <br/>
		<h3><%=tag.name %></h3>
		
		<%tag.articles.each do |article| %>
			<li style ="text-indent: 10px"><%=link_to article.title, article_path(article)%></li>
		<%end%>
		
	</ul>
	<p>_____________________<p>
<%end%>
<br/>

<%= link_to "<< Back to Article List", articles_path %>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %> </h1>

<ul>
	 <% @tag.articles.each do |article| %>
	 <li><%=link_to article.title, article_path(article) %></li>
	 <%end%>
</ul>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag user_sessions_path, method: :post do %>
	<div class ="field">
		<%=label_tag :email %>
		<%=text_field_tag :email %>
		<br/>
	</div>
	<div class ="field">
		<%= label_tag :password %>
		<%= password_field_tag :password %>
		<br/>
	</div>
	<div class ="actions">
		<%= submit_tag "Login" %>
	</div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>